export const azRegions = [
    {"region": "Central Australia", "code": "AU"},
    {"region": "Australia East", "code": "AU"},
    {"region": "Australia Southeast", "code": "AU"},
    {"region": "Austria East", "code": "AT"},
    {"region": "Belgium Central", "code": "BE"},
    {"region": "Canada East", "code": "CA"},
    {"region": "Central Canada", "code": "CA"},
    {"region": "Chile Central", "code": "CL"},
    {"region": "China East 2", "code": "CN"},
    {"region": "China North", "code": "CN"},
    {"region": "China North 2", "code": "CN"},
    {"region": "China North 3", "code": "CN"},
    {"region": "East Asia", "code": "HK"},
    {"region": "East China", "code": "CN"},
    {"region": "East Denmark", "code": "DK"},
    {"region": "East US 3", "code": "US"},
    {"region": "France Central", "code": "FR"},
    {"region": "Germany West Central", "code": "DE"},
    {"region": "India South Central", "code": "IN"},
    {"region": "Indonesia Central", "code": "ID"},
    {"region": "Israel Central", "code": "IL"},
    {"region": "Japan East", "code": "JP"},
    {"region": "Japan West", "code": "JP"},
    {"region": "Korea Central", "code": "KR"},
    {"region": "Malaysia West", "code": "MY"},
    {"region": "Mexico Central", "code": "MX"},
    {"region": "New Zealand North", "code": "NZ"},
    {"region": "Northern Europe", "code": "IE"},
    {"region": "Northern Italy", "code": "IT"},
    {"region": "Norway East", "code": "NO"},
    {"region": "Poland Central", "code": "PL"},
    {"region": "Qatar Central", "code": "QA"},
    {"region": "Saudi Arabia Central", "code": "SA"},
    {"region": "South Africa North", "code": "ZA"},
    {"region": "South India", "code": "IN"},
    {"region": "Southeast Asia", "code": "SG"},
    {"region": "Spain Central", "code": "ES"},
    {"region": "Sweden Central", "code": "SE"},
    {"region": "Switzerland North", "code": "CH"},
    {"region": "Taiwan North", "code": "TW"},
    {"region": "UAE North", "code": "AE"},
    {"region": "UK South", "code": "GB"},
    {"region": "Western Europe", "code": "NL"}
];
