//https://gist.github.com/ausfestivus/04e55c7d80229069bf3bc75870630ec8
export const azRegions = [
  {
    display_name: "East US",
    name: "eastus",
    regional_display_name: "(US) East US",
    country_code: "US",
  },
  {
    display_name: "East US 2",
    name: "eastus2",
    regional_display_name: "(US) East US 2",
    country_code: "US",
  },
  {
    display_name: "South Central US",
    name: "southcentralus",
    regional_display_name: "(US) South Central US",
    country_code: "US",
  },
  {
    display_name: "West US 2",
    name: "westus2",
    regional_display_name: "(US) West US 2",
    country_code: "US",
  },
  {
    display_name: "West US 3",
    name: "westus3",
    regional_display_name: "(US) West US 3",
    country_code: "US",
  },
  {
    display_name: "Australia East",
    name: "australiaeast",
    regional_display_name: "(Asia Pacific) Australia East",
    country_code: "AU",
  },
  {
    display_name: "Southeast Asia",
    name: "southeastasia",
    regional_display_name: "(Asia Pacific) Southeast Asia",
    country_code: "SG",
  },
  {
    display_name: "North Europe",
    name: "northeurope",
    regional_display_name: "(Europe) North Europe",
    country_code: "IE",
  },
  {
    display_name: "Sweden Central",
    name: "swedencentral",
    regional_display_name: "(Europe) Sweden Central",
    country_code: "SE",
  },
  {
    display_name: "UK South",
    name: "uksouth",
    regional_display_name: "(Europe) UK South",
    country_code: "GB",
  },
  {
    display_name: "West Europe",
    name: "westeurope",
    regional_display_name: "(Europe) West Europe",
    country_code: "NL",
  },
  {
    display_name: "Central US",
    name: "centralus",
    regional_display_name: "(US) Central US",
    country_code: "US",
  },
  {
    display_name: "South Africa North",
    name: "southafricanorth",
    regional_display_name: "(Africa) South Africa North",
    country_code: "ZA",
  },
  {
    display_name: "Central India",
    name: "centralindia",
    regional_display_name: "(Asia Pacific) Central India",
    country_code: "IN",
  },
  {
    display_name: "East Asia",
    name: "eastasia",
    regional_display_name: "(Asia Pacific) East Asia",
    country_code: "HK",
  },
  {
    display_name: "Japan East",
    name: "japaneast",
    regional_display_name: "(Asia Pacific) Japan East",
    country_code: "JP",
  },
  {
    display_name: "Korea Central",
    name: "koreacentral",
    regional_display_name: "(Asia Pacific) Korea Central",
    country_code: "KR",
  },
  {
    display_name: "Canada Central",
    name: "canadacentral",
    regional_display_name: "(Canada) Canada Central",
    country_code: "CA",
  },
  {
    display_name: "France Central",
    name: "francecentral",
    regional_display_name: "(Europe) France Central",
    country_code: "FR",
  },
  {
    display_name: "Germany West Central",
    name: "germanywestcentral",
    regional_display_name: "(Europe) Germany West Central",
    country_code: "DE",
  },
  {
    display_name: "Norway East",
    name: "norwayeast",
    regional_display_name: "(Europe) Norway East",
    country_code: "NO",
  },
  {
    display_name: "Poland Central",
    name: "polandcentral",
    regional_display_name: "(Europe) Poland Central",
    country_code: "PL",
  },
  {
    display_name: "Switzerland North",
    name: "switzerlandnorth",
    regional_display_name: "(Europe) Switzerland North",
    country_code: "CH",
  },
  {
    display_name: "UAE North",
    name: "uaenorth",
    regional_display_name: "(Middle East) UAE North",
    country_code: "AE",
  },
  {
    display_name: "Brazil South",
    name: "brazilsouth",
    regional_display_name: "(South America) Brazil South",
    country_code: "BR",
  },
  {
    display_name: "Central US EUAP",
    name: "centraluseuap",
    regional_display_name: "(US) Central US EUAP",
    country_code: "US",
  },
  {
    display_name: "Qatar Central",
    name: "qatarcentral",
    regional_display_name: "(Middle East) Qatar Central",
    country_code: "QA",
  },
  {
    display_name: "Central US (Stage)",
    name: "centralusstage",
    regional_display_name: "(US) Central US (Stage)",
    country_code: "US",
  },
  {
    display_name: "East US (Stage)",
    name: "eastusstage",
    regional_display_name: "(US) East US (Stage)",
    country_code: "US",
  },
  {
    display_name: "East US 2 (Stage)",
    name: "eastus2stage",
    regional_display_name: "(US) East US 2 (Stage)",
    country_code: "US",
  },
  {
    display_name: "North Central US (Stage)",
    name: "northcentralusstage",
    regional_display_name: "(US) North Central US (Stage)",
    country_code: "US",
  },
  {
    display_name: "South Central US (Stage)",
    name: "southcentralusstage",
    regional_display_name: "(US) South Central US (Stage)",
    country_code: "US",
  },
  {
    display_name: "West US (Stage)",
    name: "westusstage",
    regional_display_name: "(US) West US (Stage)",
    country_code: "US",
  },
  {
    display_name: "West US 2 (Stage)",
    name: "westus2stage",
    regional_display_name: "(US) West US 2 (Stage)",
    country_code: "US",
  },
  {
    display_name: "Asia",
    name: "asia",
    regional_display_name: "Asia",
    country_code: "AP",
  },
  {
    display_name: "Asia Pacific",
    name: "asiapacific",
    regional_display_name: "Asia Pacific",
    country_code: "AP",
  },
  {
    display_name: "Australia",
    name: "australia",
    regional_display_name: "Australia",
    country_code: "AU",
  },
  {
    display_name: "Brazil",
    name: "brazil",
    regional_display_name: "Brazil",
    country_code: "BR",
  },
  {
    display_name: "Canada",
    name: "canada",
    regional_display_name: "Canada",
    country_code: "CA",
  },
  {
    display_name: "Europe",
    name: "europe",
    regional_display_name: "Europe",
    country_code: "EU",
  },
  {
    display_name: "France",
    name: "france",
    regional_display_name: "France",
    country_code: "FR",
  },
  {
    display_name: "Germany",
    name: "germany",
    regional_display_name: "Germany",
    country_code: "DE",
  },
  {
    display_name: "Global",
    name: "global",
    regional_display_name: "Global",
    country_code: "GL",
  },
  {
    display_name: "India",
    name: "india",
    regional_display_name: "India",
    country_code: "IN",
  },
  {
    display_name: "Japan",
    name: "japan",
    regional_display_name: "Japan",
    country_code: "JP",
  },
  {
    display_name: "Korea",
    name: "korea",
    regional_display_name: "Korea",
    country_code: "KR",
  },
  {
    display_name: "Norway",
    name: "norway",
    regional_display_name: "Norway",
    country_code: "NO",
  },
  {
    display_name: "Singapore",
    name: "singapore",
    regional_display_name: "Singapore",
    country_code: "SG",
  },
  {
    display_name: "South Africa",
    name: "southafrica",
    regional_display_name: "South Africa",
    country_code: "ZA",
  },
  {
    display_name: "Switzerland",
    name: "switzerland",
    regional_display_name: "Switzerland",
    country_code: "CH",
  },
  {
    display_name: "United Arab Emirates",
    name: "uae",
    regional_display_name: "United Arab Emirates",
    country_code: "AE",
  },
  {
    display_name: "United Kingdom",
    name: "uk",
    regional_display_name: "United Kingdom",
    country_code: "GB",
  },
  {
    display_name: "United States",
    name: "unitedstates",
    regional_display_name: "United States",
    country_code: "US",
  },
  {
    display_name: "United States EUAP",
    name: "unitedstateseuap",
    regional_display_name: "United States EUAP",
    country_code: "US",
  },
  {
    display_name: "East Asia (Stage)",
    name: "eastasiastage",
    regional_display_name: "(Asia Pacific) East Asia (Stage)",
    country_code: "HK",
  },
  {
    display_name: "Southeast Asia (Stage)",
    name: "southeastasiastage",
    regional_display_name: "(Asia Pacific) Southeast Asia (Stage)",
    country_code: "SG",
  },
  {
    display_name: "Brazil US",
    name: "brazilus",
    regional_display_name: "(South America) Brazil US",
    country_code: "BR",
  },
  {
    display_name: "East US STG",
    name: "eastusstg",
    regional_display_name: "(US) East US STG",
    country_code: "US",
  },
  {
    display_name: "North Central US",
    name: "northcentralus",
    regional_display_name: "(US) North Central US",
    country_code: "US",
  },
  {
    display_name: "West US",
    name: "westus",
    regional_display_name: "(US) West US",
    country_code: "US",
  },
  {
    display_name: "Jio India West",
    name: "jioindiawest",
    regional_display_name: "(Asia Pacific) Jio India West",
    country_code: "IN",
  },
  {
    display_name: "East US 2 EUAP",
    name: "eastus2euap",
    regional_display_name: "(US) East US 2 EUAP",
    country_code: "US",
  },
  {
    display_name: "South Central US STG",
    name: "southcentralusstg",
    regional_display_name: "(US) South Central US STG",
    country_code: "US",
  },
  {
    display_name: "West Central US",
    name: "westcentralus",
    regional_display_name: "(US) West Central US",
    country_code: "US",
  },
  {
    display_name: "South Africa West",
    name: "southafricawest",
    regional_display_name: "(Africa) South Africa West",
    country_code: "ZA",
  },
  {
    display_name: "Australia Central",
    name: "australiacentral",
    regional_display_name: "(Asia Pacific) Australia Central",
    country_code: "AU",
  },
  {
    display_name: "Australia Central 2",
    name: "australiacentral2",
    regional_display_name: "(Asia Pacific) Australia Central 2",
    country_code: "AU",
  },
  {
    display_name: "Australia Southeast",
    name: "australiasoutheast",
    regional_display_name: "(Asia Pacific) Australia Southeast",
    country_code: "AU",
  },
  {
    display_name: "Japan West",
    name: "japanwest",
    regional_display_name: "(Asia Pacific) Japan West",
    country_code: "JP",
  },
  {
    display_name: "Jio India Central",
    name: "jioindiacentral",
    regional_display_name: "(Asia Pacific) Jio India Central",
    country_code: "IN",
  },
  {
    display_name: "Korea South",
    name: "koreasouth",
    regional_display_name: "(Asia Pacific) Korea South",
    country_code: "KR",
  },
  {
    display_name: "South India",
    name: "southindia",
    regional_display_name: "(Asia Pacific) South India",
    country_code: "IN",
  },
  {
    display_name: "West India",
    name: "westindia",
    regional_display_name: "(Asia Pacific) West India",
    country_code: "IN",
  },
  {
    display_name: "Canada East",
    name: "canadaeast",
    regional_display_name: "(Canada) Canada East",
    country_code: "CA",
  },
  {
    display_name: "France South",
    name: "francesouth",
    regional_display_name: "(Europe) France South",
    country_code: "FR",
  },
  {
    display_name: "Germany North",
    name: "germanynorth",
    regional_display_name: "(Europe) Germany North",
    country_code: "DE",
  },
  {
    display_name: "Norway West",
    name: "norwaywest",
    regional_display_name: "(Europe) Norway West",
    country_code: "NO",
  },
  {
    display_name: "Switzerland West",
    name: "switzerlandwest",
    regional_display_name: "(Europe) Switzerland West",
    country_code: "CH",
  },
  {
    display_name: "UK West",
    name: "ukwest",
    regional_display_name: "(Europe) UK West",
    country_code: "GB",
  },
  {
    display_name: "UAE Central",
    name: "uaecentral",
    regional_display_name: "(Middle East) UAE Central",
    country_code: "AE",
  },
  {
    display_name: "Brazil Southeast",
    name: "brazilsoutheast",
    regional_display_name: "(South America) Brazil Southeast",
    country_code: "BR",
  },
];
