export default [
  {
    properties: {
      roleName: "Owner",
      type: "BuiltInRole",
      description:
        "Grants full access to manage all resources, including the ability to assign roles in Azure RBAC.",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: ["*"],
          notActions: [],
          dataActions: [],
          notDataActions: [],
        },
      ],
      createdOn: "2015-02-02T21:55:09.8806423Z",
      updatedOn: "2021-11-11T20:13:45.8978856Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "8e3af657-a8ff-443c-a75c-2fe8c4bcb635",
  },
  {
    properties: {
      roleName: "User Access Administrator",
      type: "BuiltInRole",
      description: "Lets you manage user access to Azure resources.",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "*/read",
            "Microsoft.Authorization/*",
            "Microsoft.Support/*",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
        },
      ],
      createdOn: "2015-02-02T21:55:09.8806423Z",
      updatedOn: "2021-11-11T20:13:57.7932023Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/18d7d88d-d35e-4fb5-a5c3-7773c20a72d9",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "18d7d88d-d35e-4fb5-a5c3-7773c20a72d9",
  },
  {
    properties: {
      roleName: "Role Based Access Control Administrator",
      type: "BuiltInRole",
      description:
        "Manage access to Azure resources by assigning roles using Azure RBAC. This role does not allow you to manage access using other ways, such as Azure Policy.",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.Authorization/roleAssignments/write",
            "Microsoft.Authorization/roleAssignments/delete",
            "*/read",
            "Microsoft.Support/*",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
        },
      ],
      createdOn: "2022-09-07T02:29:29.6592395Z",
      updatedOn: "2023-11-09T20:56:14.1691995Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/f58310d9-a9f6-439a-9e8d-f62e7b41a168",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "f58310d9-a9f6-439a-9e8d-f62e7b41a168",
  },
  {
    properties: {
      roleName: "Azure Stack HCI Administrator",
      type: "BuiltInRole",
      description:
        "Grants full access to the cluster and its resources, including the ability to register Azure Stack HCI and assign others as Azure Arc HCI VM Contributor and/or Azure Arc HCI VM Reader",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.AzureStackHCI/register/action",
            "Microsoft.AzureStackHCI/Unregister/Action",
            "Microsoft.AzureStackHCI/clusters/*",
            "Microsoft.HybridCompute/register/action",
            "Microsoft.GuestConfiguration/register/action",
            "Microsoft.GuestConfiguration/guestConfigurationAssignments/read",
            "Microsoft.Resources/subscriptions/resourceGroups/write",
            "Microsoft.Resources/subscriptions/resourceGroups/delete",
            "Microsoft.HybridConnectivity/register/action",
            "Microsoft.Authorization/roleAssignments/write",
            "Microsoft.Authorization/roleAssignments/delete",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Management/managementGroups/read",
            "Microsoft.Support/*",
            "Microsoft.AzureStackHCI/*",
            "Microsoft.Insights/AlertRules/Write",
            "Microsoft.Insights/AlertRules/Delete",
            "Microsoft.Insights/AlertRules/Read",
            "Microsoft.Insights/AlertRules/Activated/Action",
            "Microsoft.Insights/AlertRules/Resolved/Action",
            "Microsoft.Insights/AlertRules/Throttled/Action",
            "Microsoft.Insights/AlertRules/Incidents/Read",
            "Microsoft.Resources/subscriptions/resourcegroups/deployments/read",
            "Microsoft.Resources/subscriptions/resourcegroups/deployments/write",
            "Microsoft.Resources/subscriptions/resourcegroups/deployments/operations/read",
            "Microsoft.Resources/subscriptions/resourcegroups/deployments/operationstatuses/read",
            "Microsoft.ResourceHealth/availabilityStatuses/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Resources/subscriptions/operationresults/read",
            "Microsoft.HybridCompute/machines/read",
            "Microsoft.HybridCompute/machines/write",
            "Microsoft.HybridCompute/machines/delete",
            "Microsoft.HybridCompute/machines/UpgradeExtensions/action",
            "Microsoft.HybridCompute/machines/assessPatches/action",
            "Microsoft.HybridCompute/machines/installPatches/action",
            "Microsoft.HybridCompute/machines/extensions/read",
            "Microsoft.HybridCompute/machines/extensions/write",
            "Microsoft.HybridCompute/machines/extensions/delete",
            "Microsoft.HybridCompute/operations/read",
            "Microsoft.HybridCompute/locations/operationresults/read",
            "Microsoft.HybridCompute/locations/operationstatus/read",
            "Microsoft.HybridCompute/machines/patchAssessmentResults/read",
            "Microsoft.HybridCompute/machines/patchAssessmentResults/softwarePatches/read",
            "Microsoft.HybridCompute/machines/patchInstallationResults/read",
            "Microsoft.HybridCompute/machines/patchInstallationResults/softwarePatches/read",
            "Microsoft.HybridCompute/locations/updateCenterOperationResults/read",
            "Microsoft.HybridCompute/machines/hybridIdentityMetadata/read",
            "Microsoft.HybridCompute/osType/agentVersions/read",
            "Microsoft.HybridCompute/osType/agentVersions/latest/read",
            "Microsoft.HybridCompute/machines/runcommands/read",
            "Microsoft.HybridCompute/machines/runcommands/write",
            "Microsoft.HybridCompute/machines/runcommands/delete",
            "Microsoft.HybridCompute/machines/licenseProfiles/read",
            "Microsoft.HybridCompute/machines/licenseProfiles/write",
            "Microsoft.HybridCompute/machines/licenseProfiles/delete",
            "Microsoft.HybridCompute/licenses/read",
            "Microsoft.HybridCompute/licenses/write",
            "Microsoft.HybridCompute/licenses/delete",
            "Microsoft.ResourceConnector/register/action",
            "Microsoft.ResourceConnector/appliances/read",
            "Microsoft.ResourceConnector/appliances/write",
            "Microsoft.ResourceConnector/appliances/delete",
            "Microsoft.ResourceConnector/locations/operationresults/read",
            "Microsoft.ResourceConnector/locations/operationsstatus/read",
            "Microsoft.ResourceConnector/appliances/listClusterUserCredential/action",
            "Microsoft.ResourceConnector/appliances/listKeys/action",
            "Microsoft.ResourceConnector/operations/read",
            "Microsoft.ExtendedLocation/register/action",
            "Microsoft.ExtendedLocation/customLocations/read",
            "Microsoft.ExtendedLocation/customLocations/deploy/action",
            "Microsoft.ExtendedLocation/customLocations/write",
            "Microsoft.ExtendedLocation/customLocations/delete",
            "Microsoft.EdgeMarketplace/offers/read",
            "Microsoft.EdgeMarketplace/publishers/read",
            "Microsoft.Kubernetes/register/action",
            "Microsoft.KubernetesConfiguration/register/action",
            "Microsoft.KubernetesConfiguration/extensions/write",
            "Microsoft.KubernetesConfiguration/extensions/read",
            "Microsoft.KubernetesConfiguration/extensions/delete",
            "Microsoft.KubernetesConfiguration/extensions/operations/read",
            "Microsoft.KubernetesConfiguration/namespaces/read",
            "Microsoft.KubernetesConfiguration/operations/read",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.AzureStackHCI/StorageContainers/Write",
            "Microsoft.AzureStackHCI/StorageContainers/Read",
            "Microsoft.HybridContainerService/register/action",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "((!(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})) OR (@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{f5819b54-e033-4d82-ac66-4fec3cbf3f4c, cd570a14-e51a-42ad-bac8-bafd67325302, b64e21ea-ac4e-4cdf-9dc9-5b892992bee7, 4b3fe76c-f777-4d24-a2d7-b027b0f7b273, 874d1c73-6003-4e60-a13a-cb31ea190a85,865ae368-6a45-4bd1-8fbf-0d5151f56fc1,7b1f81f9-4196-4058-8aae-762e593270df,4633458b-17de-408a-b874-0445c86b69e6})) AND ((!(ActionMatches{'Microsoft.Authorization/roleAssignments/delete'})) OR (@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{f5819b54-e033-4d82-ac66-4fec3cbf3f4c, cd570a14-e51a-42ad-bac8-bafd67325302, b64e21ea-ac4e-4cdf-9dc9-5b892992bee7, 4b3fe76c-f777-4d24-a2d7-b027b0f7b273, 874d1c73-6003-4e60-a13a-cb31ea190a85,865ae368-6a45-4bd1-8fbf-0d5151f56fc1,7b1f81f9-4196-4058-8aae-762e593270df,4633458b-17de-408a-b874-0445c86b69e6}))",
        },
      ],
      createdOn: "2023-02-06T16:01:22.3871138Z",
      updatedOn: "2023-12-06T16:25:52.5273045Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/bda0d508-adf1-4af0-9c28-88919fc3ae06",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "bda0d508-adf1-4af0-9c28-88919fc3ae06",
  },
  {
    properties: {
      roleName: "Key Vault Data Access Administrator",
      type: "BuiltInRole",
      description:
        "Manage access to Azure Key Vault by adding or removing role assignments for the Key Vault Administrator, Key Vault Certificates Officer, Key Vault Crypto Officer, Key Vault Crypto Service Encryption User, Key Vault Crypto User, Key Vault Reader, Key Vault Secrets Officer, or Key Vault Secrets User roles. Includes an ABAC condition to constrain role assignments.",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.Authorization/roleAssignments/write",
            "Microsoft.Authorization/roleAssignments/delete",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Management/managementGroups/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Support/*",
            "Microsoft.KeyVault/vaults/*/read",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "((!(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})) OR (@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{00482a5a-887f-4fb3-b363-3b7fe8e74483, a4417e6f-fecd-4de8-b567-7b0420556985, 14b46e9e-c2b7-41b4-b07b-48a6ebf60603, e147488a-f6f5-4113-8e2d-b22465e65bf6, 12338af0-0e69-4776-bea7-57ae8d297424, 21090545-7ca7-4776-b22c-e363652d74d2, b86a8fe4-44ce-4948-aee5-eccb2c155cd7, 4633458b-17de-408a-b874-0445c86b69e6})) AND ((!(ActionMatches{'Microsoft.Authorization/roleAssignments/delete'})) OR (@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{00482a5a-887f-4fb3-b363-3b7fe8e74483, a4417e6f-fecd-4de8-b567-7b0420556985, 14b46e9e-c2b7-41b4-b07b-48a6ebf60603, e147488a-f6f5-4113-8e2d-b22465e65bf6, 12338af0-0e69-4776-bea7-57ae8d297424, 21090545-7ca7-4776-b22c-e363652d74d2, b86a8fe4-44ce-4948-aee5-eccb2c155cd7, 4633458b-17de-408a-b874-0445c86b69e6}))",
        },
      ],
      createdOn: "2023-06-20T22:41:17.2192139Z",
      updatedOn: "2023-12-08T01:46:25.6834412Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/8b54135c-b56d-4d72-a534-26097cfdc8d8",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "8b54135c-b56d-4d72-a534-26097cfdc8d8",
  },
  {
    properties: {
      roleName: "Virtual Machine Data Access Administrator (preview)",
      type: "BuiltInRole",
      description:
        "Manage access to Virtual Machines by adding or removing role assignments for the Virtual Machine Administrator Login and Virtual Machine User Login roles. Includes an ABAC condition to constrain role assignments.",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.Authorization/roleAssignments/write",
            "Microsoft.Authorization/roleAssignments/delete",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Management/managementGroups/read",
            "Microsoft.Network/publicIPAddresses/read",
            "Microsoft.Network/virtualNetworks/read",
            "Microsoft.Network/loadBalancers/read",
            "Microsoft.Network/networkInterfaces/read",
            "Microsoft.Compute/virtualMachines/*/read",
            "Microsoft.HybridCompute/machines/*/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Support/*",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "((!(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})) OR (@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{1c0163c0-47e6-4577-8991-ea5c82e286e4, fb879df8-f326-4884-b1cf-06f3ad86be52})) AND ((!(ActionMatches{'Microsoft.Authorization/roleAssignments/delete'})) OR (@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{1c0163c0-47e6-4577-8991-ea5c82e286e4, fb879df8-f326-4884-b1cf-06f3ad86be52}))",
        },
      ],
      createdOn: "2023-08-08T15:31:17.1728633Z",
      updatedOn: "2023-11-01T15:17:03.5360733Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/66f75aeb-eabe-4b70-9f1e-c350c4c9ad04",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "66f75aeb-eabe-4b70-9f1e-c350c4c9ad04",
  },
  {
    properties: {
      roleName: "Defender for Storage Scanner Operator",
      type: "BuiltInRole",
      description:
        "Lets you enable and configure Microsoft Defender for Storage's malware scanning and sensitive data discovery features on your storage accounts. Includes an ABAC condition to limit role assignments.",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.Authorization/roleAssignments/write",
            "Microsoft.Authorization/roleAssignments/delete",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Management/managementGroups/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Support/*",
            "Microsoft.Security/defenderforstoragesettings/read",
            "Microsoft.Security/defenderforstoragesettings/write",
            "Microsoft.Storage/storageAccounts/write",
            "Microsoft.Storage/storageAccounts/read",
            "Microsoft.EventGrid/topics/read",
            "Microsoft.EventGrid/eventSubscriptions/read",
            "Microsoft.EventGrid/eventSubscriptions/write",
            "Microsoft.EventGrid/eventSubscriptions/delete",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "((!(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})) OR (@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{1e7ca9b1-60d1-4db8-a914-f2ca1ff27c40, d5a91429-5739-47e2-a06b-3470a27159e7})) AND ((!(ActionMatches{'Microsoft.Authorization/roleAssignments/delete'})) OR (@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{1e7ca9b1-60d1-4db8-a914-f2ca1ff27c40, d5a91429-5739-47e2-a06b-3470a27159e7}))",
        },
      ],
      createdOn: "2023-11-13T16:11:26.3567622Z",
      updatedOn: "2024-04-19T22:15:36.5164943Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/0f641de8-0b88-4198-bdef-bd8b45ceba96",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "0f641de8-0b88-4198-bdef-bd8b45ceba96",
  },
  {
    properties: {
      roleName: "Azure Sphere Owner",
      type: "BuiltInRole",
      description:
        "Allows user read and write access to Azure Sphere resources and RBAC configuration, includes an ABAC condition to constrain role assignments.",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.AzureSphere/*",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Insights/alertRules/*",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Management/managementGroups/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Support/*",
            "Microsoft.Insights/DiagnosticSettings/*",
            "Microsoft.Insights/DiagnosticSettingsCategories/Read",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
        },
        {
          actions: ["Microsoft.Authorization/roleAssignments/write"],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{8b9dfcab4b774632a6df94bd07820648,c8ae62795a0b4cb2b3f0d4d62845742c,6d994134994b4a599974f479f0b227fb,5a382001fe3641ffbba48bf06bd54da9,749f88d5cbae40b8bcfce573ddc772fa,43d0d8ad25c7471493378ba259a9fe05}",
        },
        {
          actions: ["Microsoft.Authorization/roleAssignments/delete"],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{8b9dfcab4b774632a6df94bd07820648,c8ae62795a0b4cb2b3f0d4d62845742c,6d994134994b4a599974f479f0b227fb,5a382001fe3641ffbba48bf06bd54da9,749f88d5cbae40b8bcfce573ddc772fa,43d0d8ad25c7471493378ba259a9fe05}",
        },
      ],
      createdOn: "2024-02-02T23:44:55.2967178Z",
      updatedOn: "2024-03-13T15:20:21.9497129Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/5a382001-fe36-41ff-bba4-8bf06bd54da9",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "5a382001-fe36-41ff-bba4-8bf06bd54da9",
  },
  {
    properties: {
      roleName: "Defender CSPM Storage Scanner Operator",
      type: "BuiltInRole",
      description:
        "Lets you enable and configure Microsoft Defender CSPM's sensitive data discovery feature on your storage accounts. Includes an ABAC condition to limit role assignments.",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.Storage/storageAccounts/write",
            "Microsoft.Storage/storageAccounts/read",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Management/managementGroups/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Support/*",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
        },
        {
          actions: ["Microsoft.Authorization/roleAssignments/write"],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{2a2b9908-6ea1-4ae2-8e65-a410df84e7d1, b8eda974-7b85-4f76-af95-65846b26df6d}",
        },
        {
          actions: ["Microsoft.Authorization/roleAssignments/delete"],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{2a2b9908-6ea1-4ae2-8e65-a410df84e7d1, b8eda974-7b85-4f76-af95-65846b26df6d}",
        },
      ],
      createdOn: "2024-02-26T16:08:39.4167778Z",
      updatedOn: "2024-04-19T22:15:36.5164943Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/8480c0f0-4509-4229-9339-7c10018cb8c4",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "8480c0f0-4509-4229-9339-7c10018cb8c4",
  },
  {
    properties: {
      roleName: "Azure Container Storage Contributor",
      type: "BuiltInRole",
      description:
        "Lets you install Azure Container Storage and manage its storage resources",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.KubernetesConfiguration/extensions/write",
            "Microsoft.KubernetesConfiguration/extensions/read",
            "Microsoft.KubernetesConfiguration/extensions/delete",
            "Microsoft.KubernetesConfiguration/extensions/operations/read",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Management/managementGroups/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Support/*",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
        },
        {
          actions: [
            "Microsoft.Authorization/roleAssignments/write",
            "Microsoft.Authorization/roleAssignments/delete",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "((!(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})) OR (@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{08d4c71acc634ce4a9c85dd251b4d619})) AND ((!(ActionMatches{'Microsoft.Authorization/roleAssignments/delete'})) OR (@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{08d4c71acc634ce4a9c85dd251b4d619}))",
        },
      ],
      createdOn: "2024-03-07T18:46:25.1162285Z",
      updatedOn: "2024-03-29T20:10:38.4259849Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/95dd08a6-00bd-4661-84bf-f6726f83a4d0",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "95dd08a6-00bd-4661-84bf-f6726f83a4d0",
  },
  {
    properties: {
      roleName: "Azure Container Storage Owner",
      type: "BuiltInRole",
      description:
        "Lets you install Azure Container Storage and grants access to its storage resources",
      assignableScopes: ["/"],
      permissions: [
        {
          actions: [
            "Microsoft.ElasticSan/elasticSans/*",
            "Microsoft.ElasticSan/locations/*",
            "Microsoft.ElasticSan/elasticSans/volumeGroups/*",
            "Microsoft.ElasticSan/elasticSans/volumeGroups/volumes/*",
            "Microsoft.ElasticSan/locations/asyncoperations/read",
            "Microsoft.KubernetesConfiguration/extensions/write",
            "Microsoft.KubernetesConfiguration/extensions/read",
            "Microsoft.KubernetesConfiguration/extensions/delete",
            "Microsoft.KubernetesConfiguration/extensions/operations/read",
            "Microsoft.Authorization/*/read",
            "Microsoft.Resources/subscriptions/resourceGroups/read",
            "Microsoft.Resources/subscriptions/read",
            "Microsoft.Management/managementGroups/read",
            "Microsoft.Resources/deployments/*",
            "Microsoft.Support/*",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
        },
        {
          actions: [
            "Microsoft.Authorization/roleAssignments/write",
            "Microsoft.Authorization/roleAssignments/delete",
          ],
          notActions: [],
          dataActions: [],
          notDataActions: [],
          conditionVersion: "2.0",
          condition:
            "((!(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})) OR (@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{08d4c71acc634ce4a9c85dd251b4d619})) AND ((!(ActionMatches{'Microsoft.Authorization/roleAssignments/delete'})) OR (@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{08d4c71acc634ce4a9c85dd251b4d619}))",
        },
      ],
      createdOn: "2024-03-07T18:46:25.1172293Z",
      updatedOn: "2024-03-29T20:10:38.4259849Z",
      createdBy: null,
      updatedBy: null,
    },
    id: "/subscriptions/31381ae8-323a-438d-9698-b5f4e8c3d5b5/providers/Microsoft.Authorization/roleDefinitions/95de85bd-744d-4664-9dde-11430bc34793",
    type: "Microsoft.Authorization/roleDefinitions",
    name: "95de85bd-744d-4664-9dde-11430bc34793",
  },
];
